version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: Elden
      POSTGRES_PASSWORD: Ring
      POSTGRES_DB: eldenringdb

  eldenring-app:
    image: bcahill42/eldenringbuilder:latest
    ports:
      - "5000:5000"
    environment:
      SECRET_KEY: maidenless
      DATABASE_URL: postgresql://Elden:Ring@postgres:5432/eldenringdb
    depends_on:
      - postgres